import React, { useState } from 'react'

import Layout from "../components/layout"
import Head from '../components/head'
import ParticlesBackground from '../components/particles'
import * as aboutStyles from './about.module.scss'

export default function AboutPage() {
    let quotaEnglish = "at what point did everything go wrong? They need to understand that we are many people around the world who understand the true definition of a border, and not what they think borders are. They limit and lockdown entire continents, there are many of us who understand that to free ourselfs from the chains we just need to eliminate them. Because their mentality is backwards, Wars are unnecesary, we are all the same on this planet and enyone who says otherwise doesnt deserve to be heard. we have been very patient but it is time to eliminate the cancer they are.counterattack: our first objective is to unite in a vorderless, dynamic and moving mass (lose the path, not the control) only united we can win. This movement will have self-taught culture as means of propagation. The re-culturization is the spark leading to the neo-renaissance of the soveraing citizen, because they never managed to kill what was beofre their arrival. Their retrograde vision comes from times when people did not know what was behind the montains, and it is because of this vision that their system collapsed and it is what they fail to understand. What happens is because the majority of the population on this plant knows that the system they present to us does not work, and it does a lot of damage to the planet, because their techniques are not efficient, they are wrong and we need to step them. The scientific method should have a more philosofical consencus and mathematics should rule. the relationship should be cultivated no to the mathematics per se, but to The Relationship Between Nature and Numbers. What would be the fundation of this? Some elements like fractalks, irregular patters, macro-biomimetic projects, atmospheres, orbits, and the unexplained. In reality, we are not homo sapiens but homo migratory. Basically any argument of yours is distroyed by focusing a little further than you, we do not know why you are afraid to eliminate certain imaginary borders, they think we want the unbalance, madness and chaos when in reality the only ones who bring imbalance are themselves, we want a family, house and stable work as much as you. A new map has to be drawn. A dynamic mapone of our enemies is distraction, your system works as long as you distract our attention from the most important things. the way they prevent us from bonding and sticking together is the main distraction we must eliminate in order to progress. what is the objective that is worth the most? (anything that requires an effort is worth it)"
    let quotaSpanish = "En que momento todo se fue a mal? Tienen que entender que habemos muchas personas que entienden el verdadero significado de frontera, y no lo que ustedes creen que son las fronteras. usteden limitan y trancan continentes enteros, somos muchos que entienden que para liberarnos de las cadenas solo hay que eliminarlos a ustedes. Porque la mentalidad de ustedes es muy retrasada. Las guerras son innecesarias todos somos iguales en este planeta. Y el que diga lo contrario no merece ser escuchado. Hemos sido muy pacientes pero es momento de eliminar el cancer que son. Contra-ataque: Nuestro primer objetivo es unirnos en una masa sin bordes, dinamica y cambiante (pierde el rumbo, no el control). Solo unidos podemos vencer este movimiento debe tener la cultura como medio de propagacion. la reculturacion sera la mecha que explotara esta etapa de renacimiento que comenzo a raiz de que nunca lograron matar lo que habia antes de su llegada. porque los primeros immigrantes fueron ustedes, y ahora tratan de indicar quien y quien no puede moverse por el planeta su vision retrasada viene de los tiempos en que la gente no sabia detras de las montanas, en los tiempos que barbaros llegaban a destrozar la ciudad. Y eso ya cambio, por lo mismo su systema se derrumbo y es exactamente eso lo que no logran entender. Lo que sucede es a raiz de que la mayoria de la poblacion en este planeta sabe que el sistema que nos presentan no sirve, y hace mucho dano al planeta, mas de lo necesario. Porque sus tecnicas no son las mas efficientes, lo estan haciendo mal y debemos detenerlos. El metodo cientifico debe tener un concenso mas filosofico y las matematicas deberian mandar. se debe culturizar la relacion no a la matematica per se, sino a la Relacion Entre la Naturaleza y los Numeros. cual seria la fundacion de esta? Algunos elementos como fractales, patrones irregulares (Penrose), proyectos macro-biomimeticos, atmosferas, orbitas, y lo sin explicacion. El libro de la revolucion pensara en el infinito. in reallity, we are not homo sapiens but homo migratorio. basicamente cualquier argumento suyo se destruye al enfocarse un poco mas alla que ustedes. no sabemos por que ustedes le temen a eliminar siertas fronteras imaginarias. creen que queremos el desquizio, locura y chaos cuando en realidad los unicos que traen desequilibro son ellos mismos. nosotros queremos una familia, casa y trabajo estable tanto como ustedes. hay que trazar un nuevo mapa un mapa dinamico Uno de nuestros enemigos es la distraccion. Su systema funciona mientras distraigan nuestra atencion de las cosas mas importantes. la forma en que evitan que nos unamos y mantegamos unidos es la principal distraccion que debemos eliminar para progresar. cual es el objectivo que vale mas la pena?(todo lo que merece un esfuerzo vale la pena)"
    const [language, setLanguage] = useState(quotaEnglish)


    return (
        <>
        <ParticlesBackground />
        <Layout>
            <Head title="About"/>
            <div>
                <h1 className={aboutStyles.heading}>About this centre</h1>
                <button onClick={() => setLanguage(!language)} className={aboutStyles.languageButton}>
                    {`${language ? 'Spanish' : 'English'}`}
                </button>
            </div>
            <p className={aboutStyles.paragraph}>{`${language ? quotaEnglish : quotaSpanish}`}</p>
        </Layout>
        </>
    )
}
